# Image MLflow server légère basée sur Python 3.12
FROM python:3.12-slim

RUN pip install --no-cache-dir --timeout=120 mlflow==2.21.3

# Créer le dossier de stockage (SQLite + artifacts)
RUN mkdir -p /mlflow

EXPOSE 5000

CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--backend-store-uri", "sqlite:///mlflow/mlflow.db", \
     "--default-artifact-root", "mlflow-artifacts:/", \
     "--serve-artifacts", \
     "--artifacts-destination", "/mlflow/artifacts"]
